[package]
name = "fnx-classes"
version = "0.1.0"
edition = "2024"

[dependencies]
fnx-runtime = { path = "../fnx-runtime" }
indexmap = "2.7.1"
serde = { version = "1.0.218", features = ["derive"] }

[dev-dependencies]
proptest = "1.6.0"
