[package]
name = "fnx-dispatch"
version = "0.1.0"
edition = "2024"
license-file = "../../LICENSE"

[dependencies]
fnx-runtime = { path = "../fnx-runtime" }
serde = { version = "1.0.218", features = ["derive"] }
