[package]
name = "fnx-durability"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
blake3 = "1.5.5"
raptorq = "2.0.0"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
thiserror = "2.0.11"

[dev-dependencies]
tempfile = "3.17.1"
